import type { Order } from "./types";

export const SEED_ORDERS: Order[] = [
  {
    id: "ord_26852",
    orderNumber: "26852",
    date: "2026-05-20",
    customerName: "Troy D. Pope",
    customerEmail: "twonails@yahoo.com",
    salesRep: "Alyssa Chase",
    manufacturer: "Safeguard",
    total: 20527.2,
    payment: "paid",
    status: "sfs",
    depositPaid: 2052.72,
  },
  {
    id: "ord_26851",
    orderNumber: "26851",
    date: "2026-05-20",
    customerName: "Nick Vailas",
    customerEmail: "nvailas@bedfordsurgcal.com",
    salesRep: "Reed Hunt",
    manufacturer: "Best Choice",
    total: 27501.92,
    payment: "paid",
    status: "sfs",
    depositPaid: 2750.19,
  },
  {
    id: "ord_26850",
    orderNumber: "26850",
    date: "2026-05-20",
    customerName: "Paul and Connie Woolsey",
    customerEmail: "paulwoolsey3352@gmail.com",
    salesRep: "Salita Bengochea",
    manufacturer: "Eagle",
    total: 8925.0,
    payment: "paid",
    status: "sfs",
    depositPaid: 892.5,
  },
  {
    id: "ord_26849",
    orderNumber: "26849",
    date: "2026-05-20",
    customerName: "Joshua Jordan",
    customerEmail: "jjordan8586@gmail.com",
    salesRep: "Bill Alexander",
    manufacturer: "TBS",
    total: 25933.52,
    payment: "paid",
    status: "stm",
    mfgStatus: "acknowledged",
    depositPaid: 2593.35,
  },
  {
    id: "ord_26848",
    orderNumber: "26848",
    date: "2026-05-19",
    customerName: "Joe Smalley",
    customerEmail: "joes@airworkshc.com",
    salesRep: "Tucker Fine",
    manufacturer: "American Steel",
    total: 16974.5,
    payment: "paid",
    status: "stm",
    mfgStatus: "awaiting_reply",
    depositPaid: 1697.45,
  },
  {
    id: "ord_26847",
    orderNumber: "26847",
    date: "2026-05-19",
    customerName: "Covenant Builders LLC Herbert",
    customerEmail: "cbuilders316@gmail.com",
    salesRep: "Tyler Hughes",
    manufacturer: "American Steel",
    total: 24405.08,
    payment: "paid",
    status: "stm",
    mfgStatus: "awaiting_reply",
    depositPaid: 2440.5,
  },
  {
    id: "ord_26846",
    orderNumber: "26846",
    date: "2026-05-19",
    customerName: "Craig Hellberg",
    customerEmail: "clhellberg87@yahoo.com",
    salesRep: "Liliana Arasimowicz",
    manufacturer: "American Steel",
    total: 27268.7,
    payment: "overpaid",
    status: "signed",
    depositPaid: 2726.87,
  },
  {
    id: "ord_26845",
    orderNumber: "26845",
    date: "2026-05-19",
    customerName: "Donald Clements",
    customerEmail: "clementsdonald592@gmail.com",
    salesRep: "Gabriel DeAlba",
    manufacturer: "SBS",
    total: 8776.5,
    payment: "paid",
    status: "sfs",
    depositPaid: 877.65,
  },
  {
    id: "ord_26844",
    orderNumber: "26844",
    date: "2026-05-19",
    customerName: "Phil & Karen Gates",
    customerEmail: "coolpooch@gmail.com",
    salesRep: "Gabriel DeAlba",
    manufacturer: "American Steel",
    total: 28950.17,
    payment: "paid",
    status: "stm",
    mfgStatus: "awaiting_reply",
    depositPaid: 2895.02,
  },
  // Extras to populate earlier-stage tabs:
  {
    id: "ord_26843",
    orderNumber: "26843",
    date: "2026-05-18",
    customerName: "Marcus Hollander",
    customerEmail: "m.hollander@example.com",
    salesRep: "Tucker Fine",
    manufacturer: "Safeguard",
    total: 14250.0,
    payment: "unpaid",
    status: "awaiting_signature",
    depositPaid: 0,
  },
  {
    id: "ord_26842",
    orderNumber: "26842",
    date: "2026-05-18",
    customerName: "Renee Olufsen",
    customerEmail: "rolufsen@example.com",
    salesRep: "Reed Hunt",
    manufacturer: "Eagle",
    total: 18430.0,
    payment: "partial",
    status: "pending_payment",
    depositPaid: 500,
  },
  {
    id: "ord_26841",
    orderNumber: "26841",
    date: "2026-05-18",
    customerName: "Hank Mosley",
    customerEmail: "hmosley@example.com",
    salesRep: "Salita Bengochea",
    manufacturer: "TBS",
    total: 32100.0,
    payment: "paid",
    status: "signed",
    depositPaid: 3210.0,
  },
  {
    id: "ord_26840",
    orderNumber: "26840",
    date: "2026-05-17",
    customerName: "Beatriz Salinas",
    customerEmail: "bsalinas@example.com",
    salesRep: "Bill Alexander",
    manufacturer: "American Steel",
    total: 9985.0,
    payment: "unpaid",
    status: "draft",
    depositPaid: 0,
  },
  {
    id: "ord_26839",
    orderNumber: "26839",
    date: "2026-05-16",
    customerName: "Kyle Bremer",
    customerEmail: "kbremer@example.com",
    salesRep: "Tyler Hughes",
    manufacturer: "Best Choice",
    total: 41260.0,
    payment: "paid",
    status: "stm",
    mfgStatus: "has_kickback",
    depositPaid: 4126.0,
  },
];
