import type { Order } from "./types";

export const SEED_ORDERS: Order[] = [
  {
    id: "ord_26852",
    orderNumber: "26852",
    date: "2026-05-20",
    customerName: "Troy D. Pope",
    customerEmail: "twonails@yahoo.com",
    salesRep: "Alyssa Chase",
    manufacturer: "Safeguard",
    total: 20527.2,
    payment: "paid",
    status: "sfs",
    depositPaid: 2052.72,
  },
  {
    id: "ord_26851",
    orderNumber: "26851",
    date: "2026-05-20",
    customerName: "Nick Vailas",
    customerEmail: "nvailas@bedfordsurgcal.com",
    salesRep: "Reed Hunt",
    manufacturer: "Best Choice",
    total: 27501.92,
    payment: "paid",
    status: "sfs",
    depositPaid: 2750.19,
  },
  {
    id: "ord_26850",
    orderNumber: "26850",
    date: "2026-05-20",
    customerName: "Paul and Connie Woolsey",
    customerEmail: "paulwoolsey3352@gmail.com",
    salesRep: "Salita Bengochea",
    manufacturer: "Eagle",
    total: 8925.0,
    payment: "paid",
    status: "sfs",
    depositPaid: 892.5,
  },
  {
    id: "ord_26849",
    orderNumber: "26849",
    date: "2026-05-20",
    customerName: "Joshua Jordan",
    customerEmail: "jjordan8586@gmail.com",
    salesRep: "Bill Alexander",
    manufacturer: "TBS",
    total: 25933.52,
    payment: "paid",
    status: "stm",
    mfgStatus: "acknowledged",
    depositPaid: 2593.35,
  },
  {
    id: "ord_26848",
    orderNumber: "26848",
    date: "2026-05-19",
    customerName: "Joe Smalley",
    customerEmail: "joes@airworkshc.com",
    salesRep: "Tucker Fine",
    manufacturer: "American Steel",
    total: 16974.5,
    payment: "paid",
    status: "stm",
    mfgStatus: "awaiting_reply",
    depositPaid: 1697.45,
  },
  {
    id: "ord_26847",
    orderNumber: "26847",
    date: "2026-05-19",
    customerName: "Covenant Builders LLC Herbert",
    customerEmail: "cbuilders316@gmail.com",
    salesRep: "Tyler Hughes",
    manufacturer: "American Steel",
    total: 24405.08,
    payment: "paid",
    status: "stm",
    mfgStatus: "awaiting_reply",
    depositPaid: 2440.5,
  },
  {
    id: "ord_26846",
    orderNumber: "26846",
    date: "2026-05-19",
    customerName: "Craig Hellberg",
    customerEmail: "clhellberg87@yahoo.com",
    salesRep: "Liliana Arasimowicz",
    manufacturer: "American Steel",
    total: 27268.7,
    payment: "overpaid",
    status: "signed",
    depositPaid: 2726.87,
  },
  {
    id: "ord_26845",
    orderNumber: "26845",
    date: "2026-05-19",
    customerName: "Donald Clements",
    customerEmail: "clementsdonald592@gmail.com",
    salesRep: "Gabriel DeAlba",
    manufacturer: "SBS",
    total: 8776.5,
    payment: "paid",
    status: "sfs",
    depositPaid: 877.65,
  },
  {
    id: "ord_26844",
    orderNumber: "26844",
    date: "2026-05-19",
    customerName: "Phil & Karen Gates",
    customerEmail: "coolpooch@gmail.com",
    salesRep: "Gabriel DeAlba",
    manufacturer: "American Steel",
    total: 28950.17,
    payment: "paid",
    status: "stm",
    mfgStatus: "awaiting_reply",
    depositPaid: 2895.02,
  },
  // Extras to populate earlier-stage tabs:
  {
    id: "ord_26843",
    orderNumber: "26843",
    date: "2026-05-18",
    customerName: "Marcus Hollander",
    customerEmail: "m.hollander@example.com",
    salesRep: "Tucker Fine",
    manufacturer: "Safeguard",
    total: 14250.0,
    payment: "unpaid",
    status: "awaiting_signature",
    depositPaid: 0,
  },
  {
    id: "ord_26842",
    orderNumber: "26842",
    date: "2026-05-18",
    customerName: "Renee Olufsen",
    customerEmail: "rolufsen@example.com",
    salesRep: "Reed Hunt",
    manufacturer: "Eagle",
    total: 18430.0,
    payment: "partial",
    status: "pending_payment",
    depositPaid: 500,
  },
  {
    id: "ord_26841",
    orderNumber: "26841",
    date: "2026-05-18",
    customerName: "Hank Mosley",
    customerEmail: "hmosley@example.com",
    salesRep: "Salita Bengochea",
    manufacturer: "TBS",
    total: 32100.0,
    payment: "paid",
    status: "signed",
    depositPaid: 3210.0,
  },
  {
    id: "ord_26840",
    orderNumber: "26840",
    date: "2026-05-17",
    customerName: "Beatriz Salinas",
    customerEmail: "bsalinas@example.com",
    salesRep: "Bill Alexander",
    manufacturer: "American Steel",
    total: 9985.0,
    payment: "unpaid",
    status: "draft",
    depositPaid: 0,
  },
  {
    id: "ord_26839",
    orderNumber: "26839",
    date: "2026-05-16",
    customerName: "Kyle Bremer",
    customerEmail: "kbremer@example.com",
    salesRep: "Tyler Hughes",
    manufacturer: "Best Choice",
    total: 41260.0,
    payment: "paid",
    status: "stm",
    mfgStatus: "has_kickback",
    depositPaid: 4126.0,
  },
  // ── Test orders ──────────────────────────────────────────────────────────
  // Drafts
  {
    id: "ord_26838",
    orderNumber: "26838",
    date: "2026-05-16",
    customerName: "Marcia Lindholm",
    customerEmail: "mlindholm@example.com",
    salesRep: "Alyssa Chase",
    manufacturer: "Safeguard",
    total: 12480.0,
    payment: "unpaid",
    status: "draft",
    depositPaid: 0,
  },
  {
    id: "ord_26837",
    orderNumber: "26837",
    date: "2026-05-15",
    customerName: "Derek O'Sullivan",
    customerEmail: "dosullivan@example.com",
    salesRep: "Gabriel DeAlba",
    manufacturer: "Eagle",
    total: 7800.0,
    payment: "unpaid",
    status: "draft",
    depositPaid: 0,
  },
  // Pending payment
  {
    id: "ord_26836",
    orderNumber: "26836",
    date: "2026-05-15",
    customerName: "Henrietta Fairchild",
    customerEmail: "hfairchild@example.com",
    salesRep: "Reed Hunt",
    manufacturer: "American Steel",
    total: 22150.0,
    payment: "partial",
    status: "pending_payment",
    depositPaid: 1000,
  },
  {
    id: "ord_26835",
    orderNumber: "26835",
    date: "2026-05-15",
    customerName: "Vince Castellano",
    customerEmail: "vcastellano@example.com",
    salesRep: "Tucker Fine",
    manufacturer: "TBS",
    total: 31480.5,
    payment: "unpaid",
    status: "pending_payment",
    depositPaid: 0,
  },
  {
    id: "ord_26834",
    orderNumber: "26834",
    date: "2026-05-14",
    customerName: "Joelle Whittaker",
    customerEmail: "jwhittaker@example.com",
    salesRep: "Liliana Arasimowicz",
    manufacturer: "Best Choice",
    total: 16725.0,
    payment: "partial",
    status: "pending_payment",
    depositPaid: 750,
  },
  // Awaiting signature
  {
    id: "ord_26833",
    orderNumber: "26833",
    date: "2026-05-14",
    customerName: "Otis Ramirez",
    customerEmail: "oramirez@example.com",
    salesRep: "Bill Alexander",
    manufacturer: "Safeguard",
    total: 9450.0,
    payment: "paid",
    status: "awaiting_signature",
    depositPaid: 945.0,
  },
  {
    id: "ord_26832",
    orderNumber: "26832",
    date: "2026-05-13",
    customerName: "Petra Eklund",
    customerEmail: "peklund@example.com",
    salesRep: "Salita Bengochea",
    manufacturer: "SBS",
    total: 23890.0,
    payment: "paid",
    status: "awaiting_signature",
    depositPaid: 2389.0,
  },
  {
    id: "ord_26831",
    orderNumber: "26831",
    date: "2026-05-13",
    customerName: "Wesley Brock",
    customerEmail: "wbrock@example.com",
    salesRep: "Tyler Hughes",
    manufacturer: "Eagle",
    total: 11200.0,
    payment: "paid",
    status: "awaiting_signature",
    depositPaid: 1120,
  },
  // Signed (not yet SFS)
  {
    id: "ord_26830",
    orderNumber: "26830",
    date: "2026-05-12",
    customerName: "Avery Naidoo",
    customerEmail: "anaidoo@example.com",
    salesRep: "Alyssa Chase",
    manufacturer: "American Steel",
    total: 38900.0,
    payment: "paid",
    status: "signed",
    depositPaid: 3890.0,
  },
  {
    id: "ord_26829",
    orderNumber: "26829",
    date: "2026-05-12",
    customerName: "Cassidy Wolff",
    customerEmail: "cwolff@example.com",
    salesRep: "Reed Hunt",
    manufacturer: "TBS",
    total: 14625.0,
    payment: "paid",
    status: "signed",
    depositPaid: 1462.5,
  },
  // STM — additional mfg-status variety
  {
    id: "ord_26828",
    orderNumber: "26828",
    date: "2026-05-11",
    customerName: "Quentin Hargrove",
    customerEmail: "qhargrove@example.com",
    salesRep: "Tucker Fine",
    manufacturer: "Safeguard",
    total: 52480.0,
    payment: "paid",
    status: "stm",
    mfgStatus: "acknowledged",
    co: 1,
    depositPaid: 5248.0,
  },
  {
    id: "ord_26827",
    orderNumber: "26827",
    date: "2026-05-10",
    customerName: "Ingrid Vasilescu",
    customerEmail: "ivasilescu@example.com",
    salesRep: "Gabriel DeAlba",
    manufacturer: "Best Choice",
    total: 19840.0,
    payment: "paid",
    status: "stm",
    mfgStatus: "awaiting_reply",
    depositPaid: 1984.0,
  },
  {
    id: "ord_26826",
    orderNumber: "26826",
    date: "2026-05-09",
    customerName: "Reggie Pendleton",
    customerEmail: "rpendleton@example.com",
    salesRep: "Salita Bengochea",
    manufacturer: "American Steel",
    total: 87500.0,
    payment: "overpaid",
    status: "stm",
    mfgStatus: "has_kickback",
    co: 2,
    ro: 1,
    depositPaid: 8750.0,
  },
  // Delivered (no cancellation flow)
  {
    id: "ord_26825",
    orderNumber: "26825",
    date: "2026-04-22",
    customerName: "Tabitha Onwuachu",
    customerEmail: "tonwuachu@example.com",
    salesRep: "Liliana Arasimowicz",
    manufacturer: "Eagle",
    total: 24350.0,
    payment: "paid",
    status: "delivered",
    depositPaid: 24350.0,
  },
  {
    id: "ord_26824",
    orderNumber: "26824",
    date: "2026-04-18",
    customerName: "Boyd Cunningham",
    customerEmail: "bcunningham@example.com",
    salesRep: "Bill Alexander",
    manufacturer: "TBS",
    total: 15780.0,
    payment: "paid",
    status: "delivered",
    depositPaid: 15780.0,
  },
  // Already cancelled (display-only)
  {
    id: "ord_26823",
    orderNumber: "26823",
    date: "2026-05-08",
    customerName: "Lorraine Bishop",
    customerEmail: "lbishop@example.com",
    salesRep: "Tyler Hughes",
    manufacturer: "Safeguard",
    total: 17250.0,
    payment: "paid",
    status: "cancelled",
    depositPaid: 1725.0,
  },
  {
    id: "ord_26822",
    orderNumber: "26822",
    date: "2026-05-05",
    customerName: "Garrett Aiyer",
    customerEmail: "gaiyer@example.com",
    salesRep: "Alyssa Chase",
    manufacturer: "American Steel",
    total: 9450.0,
    payment: "paid",
    status: "cancelled",
    depositPaid: 945.0,
  },
];

// Pre-seeded cancellation requests so the review queue isn't empty on first
// load after a redeploy. The in-memory store resets, so these come back.
export const SEED_CANCELLATIONS = [
  {
    id: "cnc_seed_1",
    orderId: "ord_26841", // Hank Mosley — signed
    type: "pre_stm" as const,
    status: "pending_review" as const,
    reason: "Customer changed mind",
    notes:
      "Customer called this morning, decided to delay project until next spring.",
    requestedBy: "Salita Bengochea",
    requestedAt: "2026-05-19T18:42:00Z",
    refundAmount: 3210.0,
  },
  {
    id: "cnc_seed_2",
    orderId: "ord_26848", // Joe Smalley — STM, awaiting reply
    type: "post_stm" as const,
    status: "pending_review" as const,
    reason: "Customer cancellation request",
    notes:
      "Customer's site permit was denied. Manufacturer notified, awaiting kickback amount.",
    requestedBy: "Jordan Pace",
    requestedAt: "2026-05-19T20:15:00Z",
    refundAmount: 1697.45,
  },
  {
    id: "cnc_seed_3",
    orderId: "ord_26823", // Lorraine Bishop — already cancelled
    type: "pre_stm" as const,
    status: "approved" as const,
    reason: "Financing fell through",
    notes: "Customer's bank denied the loan application.",
    requestedBy: "Tyler Hughes",
    requestedAt: "2026-05-08T14:00:00Z",
    refundAmount: 1725.0,
    decidedAt: "2026-05-08T16:30:00Z",
    decidedBy: "Rex Wu",
    decisionNotes: "Approved. Refund initiated via Stripe.",
  },
];

